import { supabase } from '../supabaseClient';

// Helper to map DB snake_case to App camelCase
const mapClientFromDB = (dbClient) => ({
    ...dbClient,
    fullName: dbClient.full_name,
    salesmanId: dbClient.salesman_id,
    socialMedia: dbClient.social_media,
    updatedAt: dbClient.updated_at,
    // Remove snake_case keys if desired, or keep them. 
    // Spreading first then overwriting ensures we have both or just the ones we need.
});

// Helper to map App camelCase to DB snake_case
const mapClientToDB = (client) => ({
    full_name: client.fullName,
    phone: client.phone,
    email: client.email,
    notes: client.notes,
    salesman_id: client.salesmanId,
    social_media: client.socialMedia,
    website: client.website,
    // id is auto-generated by DB on insert usually, but if we pass it:
    ...(client.id && { id: client.id })
});

export const dataService = {
    // Clients
    getClients: async () => {
        let allClients = [];
        let from = 0;
        const step = 1000;
        let more = true;

        while (more) {
            const { data, error } = await supabase
                .from('clients')
                .select('*')
                .order('created_at', { ascending: false })
                .range(from, from + step - 1);

            if (error) {
                console.error('Error fetching clients:', error);
                return [];
            }

            if (data.length > 0) {
                allClients = allClients.concat(data);
                from += step;
                if (data.length < step) {
                    more = false; // Last page
                }
            } else {
                more = false;
            }
        }

        return allClients.map(mapClientFromDB);
    },

    getClientCount: async () => {
        const { count, error } = await supabase
            .from('clients')
            .select('*', { count: 'exact', head: true });

        if (error) {
            console.error('Error counting clients:', error);
            return 0;
        }
        return count;
    },

    getRecentClients: async (limit = 5) => {
        const { data, error } = await supabase
            .from('clients')
            .select('*')
            .order('updated_at', { ascending: false })
            .limit(limit);

        if (error) {
            console.error('Error fetching recent clients:', error);
            return [];
        }
        return data.map(mapClientFromDB);
    },

    addClient: async (client) => {
        const dbClient = mapClientToDB(client);
        // Remove ID to let DB generate it, or handle it if you want client-side UUIDs
        delete dbClient.id;

        const { data, error } = await supabase
            .from('clients')
            .insert([dbClient])
            .select()
            .single();

        if (error) throw error;
        return mapClientFromDB(data);
    },

    updateClient: async (id, updates) => {
        const dbUpdates = {};
        if (updates.fullName !== undefined) dbUpdates.full_name = updates.fullName;
        if (updates.phone !== undefined) dbUpdates.phone = updates.phone;
        if (updates.email !== undefined) dbUpdates.email = updates.email;
        if (updates.notes !== undefined) dbUpdates.notes = updates.notes;
        // Handle salesman_id: if empty string, set to null (or keep as is if your schema allows empty string FKs, but null is safer for 'unassigned')
        if (updates.salesmanId !== undefined) dbUpdates.salesman_id = updates.salesmanId || null;
        if (updates.socialMedia !== undefined) dbUpdates.social_media = updates.socialMedia;
        if (updates.website !== undefined) dbUpdates.website = updates.website;

        const { data, error } = await supabase
            .from('clients')
            .update(dbUpdates)
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return mapClientFromDB(data);
    },

    deleteClient: async (id) => {
        const { error } = await supabase
            .from('clients')
            .delete()
            .eq('id', id);
        if (error) throw error;
    },

    // Salesmen
    getSalesmen: async () => {
        const { data, error } = await supabase
            .from('salesmen')
            .select('*')
            .order('name');

        if (error) {
            console.error('Error fetching salesmen:', error);
            return [];
        }
        return data; // Salesmen table uses simple names that match (name, email, phone, id)
    },

    addSalesman: async (salesman) => {
        // Salesman object keys (name, email, phone) match DB columns
        const { data, error } = await supabase
            .from('salesmen')
            .insert([salesman])
            .select()
            .single();

        if (error) throw error;
        return data;
    },

    deleteSalesman: async (id) => {
        const { error } = await supabase
            .from('salesmen')
            .delete()
            .eq('id', id);
        if (error) throw error;
    }
};
